Repository aquasecurity/libbpfgo, pull requests merged in 2022-09, with the labels that each got.

#235 fix Makefiles typos
  Makefile
  selftest/common/Makefile
  selftest/uprobe/Makefile
  selftest/version/Makefile
  selftest/xdp/Makefile
Labels: bug

#239 makefile: fix vmlinuxh rule
  Makefile
Labels: bug

#237 builder: vagrant: introduce Vagrantfile
  .gitignore
  Makefile
  Readme.md
  builder/Vagrantfile-ubuntu
  builder/prepare-ubuntu.sh
  docs/Vagrantfile.md
Labels: enhancement

#241 kernel_symbols: cache symbols by addr
  helpers/kernel_symbols.go
Labels: optimization

#244 Add workaround to CGO bug
  libbpfgo.go
Labels: bug
