Repository aquasecurity/libbpfgo, pull requests merged in 2024-04, with the labels that each got.

#412 Optionally enable kernel logging
  libbpfgo.c
  libbpfgo.h
  module.go
Labels: feature

#414 fix: ping localhost instead
  selftest/iter/main.go
Labels: bug

#417 chore(ci): bump setup-go action to v5
  .github/actions/build-dependencies/action.yaml
Labels: chore
